apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-app-deployment-gcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit-app
  template:
    metadata:
      labels:
        app: reddit-app
    spec:
      containers:
      - name: reddit-app-container
        image: us-central1-docker.pkg.dev/nirant-lab9/reddit-repo/reddit-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        command: ["uvicorn"]
        args: ["redditApp:app", "--host", "0.0.0.0", "--port", "8000"]
